In [1]:
import pandas as pd

df = pd.read_csv("../data/delivery_times.csv")

df.head()

   distance_km  prep_time_min traffic_level  rain  delivery_min
0         6.24             19        Medium     1          57.4
1        14.31             16        Medium     0          67.3
2        11.25             34           Low     1          75.3
3         9.38             20        Medium     0          62.2
4         3.18             28           Low     0          41.7

In [2]:
df.shape

(1000, 5)

In [3]:
df.isnull().sum()

distance_km      0
prep_time_min    0
traffic_level    0
rain             0
delivery_min     0
dtype: int64

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   distance_km    1000 non-null   float64
 1   prep_time_min  1000 non-null   int64
 2   traffic_level  1000 non-null   str
 3   rain           1000 non-null   int64
 4   delivery_min   1000 non-null   float64
dtypes: float64(2), int64(2), str(1)
memory usage: 39.2 KB

In [5]:
df["traffic_level"].unique()

<StringArray>
['Medium', 'Low', 'High']
Length: 3, dtype: str

In [6]:
df["traffic_level"] = df["traffic_level"].map({
    "Low": 1,
    "Medium": 2,
    "High": 3
})

df.head()

   distance_km  prep_time_min  traffic_level  rain  delivery_min
0         6.24             19              2     1          57.4
1        14.31             16              2     0          67.3
2        11.25             34              1     1          75.3
3         9.38             20              2     0          62.2
4         3.18             28              1     0          41.7

In [7]:
X = df[[
    "distance_km",
    "prep_time_min",
    "traffic_level",
    "rain"
]]

y = df["delivery_min"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (1000, 4)
y shape: (1000,)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (800, 4)
Testing data: (200, 4)

In [9]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [10]:
y_pred = model.predict(X_test)

print(y_pred[:10])

[41.35740285 66.697647   69.29351645 39.70251608 70.93940575 52.82357245
 64.35060034 63.45992007 43.31060173 47.49512425]

In [11]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)

print("MAE:", mae)

MAE: 2.4150685860206402

In [12]:
from sklearn.tree import DecisionTreeRegressor

tree_model = DecisionTreeRegressor(
    max_depth=5,
    random_state=42
)

tree_model.fit(X_train, y_train)

tree_pred = tree_model.predict(X_test)

tree_mae = mean_absolute_error(y_test, tree_pred)

print("Decision Tree MAE:", tree_mae)

Decision Tree MAE: 5.279524991228264

In [13]:
from sklearn.ensemble import RandomForestRegressor

forest_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

forest_model.fit(X_train, y_train)

forest_pred = forest_model.predict(X_test)

forest_mae = mean_absolute_error(y_test, forest_pred)

print("Random Forest MAE:", forest_mae)

Random Forest MAE: 3.174114999999999

In [14]:
results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "MAE": [
        mae,
        tree_mae,
        forest_mae
    ]
})

results.sort_values("MAE")

               Model       MAE
0  Linear Regression  2.415069
2      Random Forest  3.174115
1      Decision Tree  5.279525

In [15]:
from sklearn.metrics import mean_squared_error
import numpy as np

baseline_prediction = y_train.mean()

baseline_pred = np.full(
    len(y_test),
    baseline_prediction
)

baseline_mae = mean_absolute_error(y_test, baseline_pred)
baseline_rmse = np.sqrt(mean_squared_error(y_test, baseline_pred))

print("Baseline MAE:", baseline_mae)
print("Baseline RMSE:", baseline_rmse)

Baseline MAE: 12.159499999999998
Baseline RMSE: 14.641617192100057

In [16]:
linear_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
tree_rmse = np.sqrt(mean_squared_error(y_test, tree_pred))
forest_rmse = np.sqrt(mean_squared_error(y_test, forest_pred))

print("Linear Regression RMSE:", linear_rmse)
print("Decision Tree RMSE:", tree_rmse)
print("Random Forest RMSE:", forest_rmse)

Linear Regression RMSE: 2.99616501120844
Decision Tree RMSE: 6.356856296525999
Random Forest RMSE: 3.990743239673531

In [17]:
results = pd.DataFrame({
    "Model": [
        "Baseline",
        "Linear Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "MAE": [
        baseline_mae,
        mae,
        tree_mae,
        forest_mae
    ],
    "RMSE": [
        baseline_rmse,
        linear_rmse,
        tree_rmse,
        forest_rmse
    ]
})

results.sort_values("MAE")

               Model        MAE       RMSE
1  Linear Regression   2.415069   2.996165
3      Random Forest   3.174115   3.990743
2      Decision Tree   5.279525   6.356856
0           Baseline  12.159500  14.641617

In [18]:
import sklearn

print("scikit-learn version:", sklearn.__version__)

scikit-learn version: 1.8.0